replicaCount: 1

ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - name: sonar.k8s.lab.miaguila.com
      path: /
  annotations:
    external-dns.alpha.kubernetes.io/hostname: sonar.k8s.lab.miaguila.com
    external-dns.alpha.kubernetes.io/ttl: "30"
    cert-manager.io/cluster-issuer: acme-staging
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

  tls:
    - hosts:
      - sonar.k8s.lab.miaguila.com
      secretName: sonar-cert

database:
  type: "postgresql"

postgresql:
  enabled: true
  postgresqlUsername: "sonarUser"
  postgresqlPassword: "uHr-AsuDK@X*6G286KjBx9kv"
  postgresqlDatabase: "uHr-AsuDK@X*6G286KjBx9kv"
  service:
    port: 5432