apiVersion: v2
name: argo-notifications
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: argocd-notifications
  version: 1.4.4
  repository: https://argoproj.github.io/argo-helm
